### PR TITLE
Add Bookdown project

### PR DESCRIPTION
**Pull request by jakejohns**

### CODE REVIEW

**Comment by calavera** [comment]
I'm closing this PR because it's a duplicated of #177.

**Comment by jakejohns** [comment]
It is not. They are different projects actually.

**Comment by calavera** [comment]
Gosh, sorry about that. Reopened.

**Comment by calavera** [comment]
LGTM

**Comment by calavera** [comment]
@jakejohns there is a conflict now with the file names. And I'm thinking that there will be a conflict with names in the UI. I'm not sure what the best way to proceed, but I feel like showing two projects with the same name might be very confusion for people. Can you add something like `(PHP)` in the name attribute?

**Comment by znmeb** [comment]
Yeah - call them Bookdown (R) and Bookdown (PHP). And check whether either of them has filed a trademark just in case.

**Comment by jakejohns** [comment]
Better? Sorry for the delay.

**Comment by calavera** [comment]
LGTM, thanks @jakejohns

**Pull request merged**
