### PR TITLE
Update redirects

### PR DESCRIPTION
**Pull request by huguestennier**
### Test plan

https://deploy-preview-903--staticgen.netlify.app/ -> `/generators/`
https://deploy-preview-903--staticgen.netlify.app/about -> `/generators/`
https://deploy-preview-903--staticgen.netlify.app/next -> `/generators/next/`

### CODE REVIEW

**Review by scottmathson — APPROVED** [review]
right on! thanks
image

**Comment by lex111** [comment]
Sorry, I may not understand something, but why did you remove the leaderboard of static gens? After all, the beauty of your wonderful site was that the number of stars was visible in last time.. this allowed to watch the trend of project.

**Comment by huguestennier** [comment]
We're consolidating properties (both staticgen.com and headlesscms.org) to jamstack.org to make them more discoverable and build even more features.

The leaderboard / sorting / filtering is definitely not going away! We had a sharp deadline and we had to make difficult decisions for the launch - but rest assured, these are not removed. They'll be back in the next couple of days/weeks

**Comment by lex111** [comment]
Awesome, thank you for your work! :heart:

**Pull request merged**
