### PR TITLE
Added JAQ

### PR DESCRIPTION
**Pull request by johncarl81**

### CODE REVIEW

**Comment by biilmann** [comment]
screen shot 2015-05-04 at 5 01 46 pm

Might be good to abbreviate the title, the long title breaks the layout...

**Comment by johncarl81** [comment]
Good catch.  Thanks!

By the way, I made a guess at the Template, is Liquid correct?  Or should
it be Asciidoc?

**Comment by biilmann** [comment]
Yeah, from the description it looks like JAQ replaces Markdown with Asciidoc but keeps Liquid for templating, right?

Btw, check out our hosting product, [netlify](https://www.netlify.com). All those steps with Travis+Github tokens, etc - can basically be replaced with one click with netlify :)

**Comment by johncarl81** [comment]
Cool, I'll have to check it out.

**Pull request merged**
