### PR TITLE
unify license name

### PR DESCRIPTION
**Pull request by noraj**

### CODE REVIEW

**Comment by erquhart** [comment]
Weird I could have sworn I standardized all of these a while back. We're trying to use the standardized short identifiers from the Linux Foundation's SPDX license list - can you update the changed files to use those?

https://spdx.org/licenses/

**Comment by noraj** [comment]
I'll do that in a few days.

**Comment by noraj** [comment]
Let's pretend all GPL family license are version only because it would consume to much time to check if they are version only or version and later.

**Comment by noraj** [comment]
:heavy_check_mark: done @erquhart

**Comment by noraj** [comment]
bump @erquhart

**Comment by erquhart** [comment]
So sorry for the delay on this - thanks @noraj!

**Pull request merged**
