### PR TITLE
Add Kotsu

### PR DESCRIPTION
**Pull request by ArmorDarks**
Another day, another static site generator :)

Opened in favor of https://github.com/netlify/staticgen/pull/313

### CODE REVIEW

**Comment by ArmorDarks** [comment]
@bdougie Strange, still same error =\

**Comment by bdougie** [comment]
This is a new error on master and I not sure of the cause just yet.

**Comment by ArmorDarks** [comment]
The error is here: https://github.com/netlify/staticgen/pull/314/files#diff-de9c4a04ee5101114c597581e9ba9361R8

Line should be taken into quotes since it contains `:`

```yaml
description: 'One word: TextToWebsite. Sasige will generate static html files and a combination of these is your website.'
```

**Comment by bdougie** [comment]
Great Catch @ArmorDarks!

**Pull request merged**
