### PR TITLE
Add lazy-travel-blog

### PR DESCRIPTION
**Pull request by martin-martin**

### CODE REVIEW

**Comment by martin-martin** [comment]
Made this little project for myself on a trip that creates a quick static travel blog. I realized it's basically a static page generator, so when I was looking through your project, I thought it might be the place to add it :)

**Comment by erquhart** [comment]
Awesome, thanks for adding!

**Comment by martin-martin** [comment]
Hei @erquhart thanks for merging--I was wondering is there something else I need to do so the project goes live on <https://staticgen.com>? It's currently not displaying, even though it's in the `master` branch. Thanks!

**Comment by erquhart** [comment]
Staticgen is pending some maintenance, will be updated soon.

**Pull request merged**
