### PR TITLE
Add tumblelog; both the Perl and Python version

### PR DESCRIPTION
**Pull request by john-bokma**

### CODE REVIEW

**Comment by zachleat** [comment]
If the name and repo are the same—does it make more sense to have one entry for these and add two languages under support?

**Comment by john-bokma** [comment]
> If the name and repo are the same—does it make more sense to have one entry for these and add two languages under support?

Good question. I have given this some thought and was afraid that listing two languages would give the impression that the project requires both in order to run.

**Comment by zachleat** [comment]
Ah, fair enough—thanks!

**Comment by john-bokma** [comment]
Thank you very much for the merge.

**Pull request merged**
