### PR TITLE
Add Franklin

### PR DESCRIPTION
**Pull request by Hugo-Trentesaux**
Add Franklin static site generator as in #774

### CODE REVIEW

**Comment by fusion809** [comment]
I've reviewed the changes and I see no problems. I hope this PR gets merged soon.

**Comment by Hugo-Trentesaux** [comment]
Looks like this PR has been ignored.

**Comment by zachleat** [comment]
We’re working through a backlog right now—thank you for your patience!

**Comment by zachleat** [comment]
Shipping, thanks!

**Pull request merged**
