### PR TITLE
add nsm (nifty site manager)

### PR DESCRIPTION
**Pull request by n-ham**
Added nifty-site-manager.md to content/projects, let me know if there's anything else needed to add nsm to the list of site managers on https://www.staticgen.com/.

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks for adding! I'm not certain what the templates selection indicates - are "dev", "null", and "simple" referring to actual template syntaxes?

**Comment by n-ham** [comment]
When one does `nsm init-null`, `nsm init-dev` or `nsm init-simple` then nsm will initialise managing a site with the specified site files from https://gitlab.com/nsm-templates. Alternatively one can just fork and rename one of the template repositories then clone using `nsm clone repository-url` (I have users cloning using nsm so it can set up a few extra things, especially for bitbucket and github). I am working on ginit versions of my init functions today that will set up what the nsm clone command does with the branches, ie. on BitBucket/GitHub I have a stage branch that includes everything including the site directory, however the site directory is the master/gh-pages branch including the site files). Changes can be built, committed and pushed back to BitBucket/GitHub/GitLab using `nsm bcp "commit message"` too.

I hope that answers your question? I am curious where you saw dev/null/simple too?

**Comment by n-ham** [comment]
I have added in `nsm ginit (page-name)`, `nsm ginit-null (page-name)`, `nsm ginit-dev (page-name)` and `nsm ginit-simple (page-name)` as nsm commands, and added them to the nsm commands part of the documentation part of the nsm website.

**Comment by erquhart** [comment]
I'm not sure I follow - the `templates` field should list _templating languages_ that a static site generator supports. For example, Jekyll supports the Liquid template language. `null`, `dev` and `simple` appear to be individual site templates - what template languages does nsm support?

**Comment by n-ham** [comment]
Oh I see what you were asking about now. Based on other site managers using custom as the template language option, I guess that applies best here and have updated to that. The best places to see what the 'template language' is for nsm is the [template files](https://nifty-site-manager.com/documentation/template_files.html) and [content files](https://nifty-site-manager.com/documentation/content.html) pages from the docs. Though people can use any languages in those files as well, html, css, js, jquery, php, etc. etc..

**Comment by erquhart** [comment]
Looks great, thanks!

**Pull request merged**
