### PR TITLE
Add elm-pages.

### PR DESCRIPTION
**Pull request by dillonkearns**

### CODE REVIEW

**Comment by dillonkearns** [comment]
Thank you!

**Comment by erquhart** [comment]
No problem, thanks for adding!

**Comment by dillonkearns** [comment]
By the way, should the changes be live by now? No rush, just wanted to make sure there weren't any hiccoughs with the deploy pipeline.

 I'm not seeing elm-pages at staticgen.com, and I also noticed [the recent changes for Hikaru](https://www.staticgen.com/hikaru) are not reflected either (it changed from CoffeeScript to JavaScript, but it still stays CoffeeScript on the live site).

**Comment by erquhart** [comment]
No, the site itself actually has some issues and is slated for maintenance. You'll see the update after that.

**Comment by dillonkearns** [comment]
Sounds good, thanks for the info!

**Pull request merged**
