### PR TITLE
Fixing a number of broken links/updating references

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @erquhart,

I've done some research around static site generators and found staticgen.com super useful! Thank you!

During the research I've found a bunch of outdated/broken links. If possible I've updated/replaced the links or if no source was to find/identify completely removed. Let me know if you got any questions!

Peter

### CODE REVIEW

**Comment by erquhart** [comment]
Super helpful, thanks! You added a link to a blog post of yours, but it's broken (rather ironic lol) - it might be good to link somewhere that's very unlikely to change, eg. https://davidwalsh.name/introduction-static-site-generators

**Comment by spekulatius** [comment]
Hello @erquhart,

this is indeed hilarious. That's the blog article, I did my research for 😂️ I want to share some information I collected myself and make the topic more accessible.

I've compared the articles and found the one by Eduardo Bouças on David Welsh' site is a bit dated (2015). It doesn't include nice things or doesn't highlight some more modern parts (solutions for workarounds with Netlify Forms & CMS for example). I hope to have this included well enough. I've also fixed the link 😂️ I'm happy to update/include more, if you think it needs to 👍️ Of course, I can also just swap it out (if you want). 

Let me know what you think.

Cheers,
Peter

**Comment by erquhart** [comment]
Fixed link works for me - thanks again for the updates!

**Comment by spekulatius** [comment]
No problem. Thanks for pointing it out!

**Comment by Sirikon** [comment]
I'll just point out here that @spekulatius is being pretty agressive with the link of his post including it in many other repositories https://github.com/Sirikon/pitch/pull/8#issuecomment-494561115

He's even quantifying the links he gets from different repositories, like here: https://github.com/seymoe/reactpress/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8R2 (Notice the utm_source and utm_medium).

I would suggest replacing it with https://davidwalsh.name/introduction-static-site-generators as pointed out initially by @erquhart , because Spekulatius' interests seem to be more personal than for the community's good, the Eduardo's post is better in terms of explanation and examples, and the part of highlighting modern solutions is already done by https://www.staticgen.com/.

**Comment by spekulatius** [comment]
Hello @Sirikon 

valid critic and I accept it. The original intention was to fix the broken links to the same non-existing resource, but I got carried away. I've made a mistake by adding these links and I'll close the related PRs. Just on the side: I've got no advantages from the links - it's a personal blog, where I write about coding & tech 🙏️

Peter

**Pull request merged**
