### PR TITLE
Add Kotsu

### PR DESCRIPTION
**Pull request by ArmorDarks**
Another day, another static site generator :)

### CODE REVIEW

**Comment by ArmorDarks** [comment]
pinging @bdougie, just in case...

**Comment by ArmorDarks** [comment]
another try... @biilmann

**Comment by bdougie** [comment]
Need to rebase master @ArmorDarks. There was an unrelated error causing this build to fail.

https://github.com/netlify/staticgen/commit/0399a59ffbe903a8e937154cb4f666883bb5ec14

**Comment by ArmorDarks** [comment]
I can no longer fast-forward to current master. New PR here https://github.com/netlify/staticgen/pull/315

**Pull request closed without merging**
