### PR TITLE
add Antora

### PR DESCRIPTION
**Pull request by mojavelinux**
Add Antora to the catalog. See https://antora.org.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Is there anything else I can do to make this merge ready?

**Comment by erquhart** [comment]
Nope, sorry for the wait - thanks for adding!

**Comment by mojavelinux** [comment]
Thanks @erquhart!

**Comment by mojavelinux** [comment]
It looks like the link to GitLab doesn't work. What's the correct syntax? It seems that staticgen is assuming the project is on GitHub.

https://www.staticgen.com/antora

**Comment by mojavelinux** [comment]
The assumption seems to be here: https://github.com/netlify/staticgen/blob/master/src/Project/Project.js#L100-L102. Not all projects live on GitHub ;)

**Comment by erquhart** [comment]
Argh, forgot we were holding off on this: https://github.com/netlify/staticgen/pull/429

**Comment by mojavelinux** [comment]
Thanks for the pointer. To give the issue more visibility, I've created a dedicated issue for GitLab support. See https://github.com/netlify/staticgen/issues/510.

**Pull request merged**
