### PR TITLE
Migrate to Gatsby

### LINKED ISSUE #384: Extract css chunks now  supports Webpack 4
Hey guys. Just letting you know the css chunking plugin, and the whole universal family is now Webpack 4 compatible with major version bumps ♥️♥️

### LINKED ISSUE #422: Possible caching issue
I've been playing around with this project locally and have come across a possible issue.

1. `git clone https://github.com/netlify/staticgen`
2. `npm install`
3. `npm start`
4. Delete one or more files from the `projects` folder
5. Refresh browser and see deleted projects still visible on the homepage
6. Stop development server
7. Delete the GitHub Gist `staticgen-archive.json`
8. Delete `tmp` and `dist`
9. `npm start`
10. Note the deleted projects are still visible on the homepage
11. Note the deleted project data still exists in the newly generated `tmp` and Gist caches. I have no idea where it keeps pulling the deleted project data from to generate those `JSON` caches.

If I click on a deleted project on the homepage it will show an error (`TypeError: _react2.default.createRef is not a function`) rather than a 404 page.

Node version: v9.4.0
npm version: 5.6.0
Firefox 62.0
macOS 10.13.6

### LINKED ISSUE #479: Upgrade to React Static 6
Address all breaking changes: https://github.com/nozzle/react-static/blob/master/CHANGELOG.md#breaking-changes

### LINKED ISSUE #513: Would it be possible to add sort by "stars growth"
Hey folks 👋 

I find the way that you're displaying the growth of stars by product very interesting and very useful 🎉 I'm wondering if it's possible to add sorting by "stars growth" to the sort dropdown 🤔 

I took a quick look at the implementation and it seems a bit complicated at first glance. If it is something that you think might be interesting to add then I might take another look at it 👍

### LINKED ISSUE #534: Broken github repo links in projects added since 07/23
The link to the github repo is treated as relative and https://github.com is not appended to the URL. Docsify for example has `href="docsifyjs/docsify"`, thus the link is to https://www.staticgen.com/docsifyjs/docsify

Affected pages:
* https://www.staticgen.com/haunt
* https://www.staticgen.com/docsify
* https://www.staticgen.com/soupault

At first I thought I've messed up the repo field, but then I checked that everything else also uses relative "user/repo" link in that field, but only projects merged in yesterday are affected.

### LINKED ISSUE #541: Migrate to Gatsby
It may be time to move this project to Gatsby. The migration would impact this repo as well as [headlesscms.org](https://github.com/netlify/headlesscms.org).

I'd expect it to look something like this:

1. Migrate Twitter, GitHub, and GitLab data fetching logic to proper Gatsby source plugins (use headlesscms.org source for this)
2. Create a Gatsby Theme based on the components used in headlesscms.org (updated most recently)
3. Update both staticgen and headlesscms.org to use the new theme and plugins

Have not vetted this plan fully, more consideration is needed before someone jumps in.

### LINKED ISSUE #600: Bashblog-ng not showing
Bashblog-ng was added in https://github.com/netlify/staticgen/commit/8226c576be15a907ff0bc946a7278df0e4632eef and later approved and merged into the repo. That is however many weeks ago and it still does not show up on the website. Bashblog-ng is a fork of Bashblog (that's already on the site) - is this somehow part of the problem?

### LINKED ISSUE #634: Unable to setup local build
The `README.md` document is not in sync with the current build environment used and due to this not able to setup it locally.

### PR DESCRIPTION
**Pull request by erquhart**
See #541 for context. Migrates site to Gatsby, positions us to convert the core to a Gatsby theme shared by this repo and headlesscms.org.

Closes #634 
Closes #600 
Closes #541 
Closes #534 
Closes #513 
Closes #479 
Closes #422 
Closes #384

### CODE REVIEW

**Comment by dmbaturin** [comment]
"About" and "Contributing" are displayed on the main page as if they were static generators, not special pages.

**Comment by erquhart** [comment]
Argh good catch, thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dmbaturin** [comment]
Another thing: links are all wrong! For example, the card of "yst" actually points to https://www.staticgen.com/heckle

**Comment by erquhart** [comment]
@dmbaturin both seem to be fixed now

**Comment by dmbaturin** [comment]
@erquhart The issue with "contributing" and "about" having cards on the main page is fixed, but the issue with messed up links got more interesting. 
The Nanoc card now points to Nikola and vice versa, for example. Many other links point to seemingly random wrong places.

**Comment by erquhart** [comment]
I haven’t been able to reproduce, those two cards are linking correctly as far as I can tell. Are there steps to take?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dmbaturin** [comment]
@erquhart Ok, sorry, this is a bit different issue. When clicked, the cards take you to the right place. However, the tooltips are wrong when the page first loads.
Clicking on a card and going back fixes it somehow, but reloading the page makes it appear again.

**Comment by erquhart** [comment]
Ah okay I’ll take a look

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
