### PR TITLE
Adding Antora

### PR DESCRIPTION
**Pull request by mere-teresa**
Antora is a static gen. in Node, based on ASCIIdoc documents

### CODE REVIEW

**Comment by philhawksworth** [comment]
Sorry for the delay in merging this. 

We'll just need a small change in our site logic which appears to assume all repos are in GitHub rather than possible residing in GitLab (as this one does).

Once we ship that change, we can merge this in.

**Comment by briandominick** [comment]
Is this GitLab accommodation still in the works?

**Comment by erquhart** [comment]
No one has taken that on just yet, it's available to be claimed/implemented if anyone is interested.

**Comment by mojavelinux** [comment]
I submitted an entry for Antora and it was accepted. However, we still have the GitLab issue. I've created a dedicated issue to track it. See https://github.com/netlify/staticgen/issues/510.

**Comment by mojavelinux** [comment]
I've submitted a PR for this support. Feedback welcome. See #511.

**Comment by mojavelinux** [comment]
I was not aware of this PR until after I submitted mine. Though, as the owner of the project, I felt it was my duty to provide the official text. Had I been aware of your PR, I would have proposed a revision to it instead. To be honest, it didn't even dawn on me to check.

As for the status, the entry has since been reverted because of the lack of GitLab support. Therefore, I could take this opportunity to propose my updates to this PR since it's still update. So, in the end, we're back to square one ;)

**Comment by mojavelinux** [comment]
I've sent an update to this PR.

**Comment by mojavelinux** [comment]
The repo field may have to change depending on what happens with #510.

**Comment by erquhart** [comment]
This was resolved by in #510, which also adds support for GitLab projects!!

@mere-teresa thanks so much for opening this PR! As @mojavelinux is the creator/maintainer of Antora, I asked him to include the description that he preferred in the GitLab PR for expedience and accuracy. Glad to have Antora up on the board 🎉 💪

**Comment by mojavelinux** [comment]
Thank you @erquhart!!

**Comment by mojavelinux** [comment]
And we already have +1 star for Antora, so it's nice to see it all working!

**Pull request closed without merging**
