### PR TITLE
Create dwttool.md

### PR DESCRIPTION
**Pull request by kambrium**

### CODE REVIEW

**Comment by biilmann** [comment]
I don't see any instructions in the dwttool README on using it to generate static sites, so I'm not sure it qualifies for this listing.

**Comment by kambrium** [comment]
Well, dwttool's approach is a bit different. At first, create a new project (`dwttool create project`) and edit the template so that it contains all elements that should appear on every page. Then, create pages based on the template with `dwttool create page`. Insert the page specific content between the DWT tags `<!-- #BeginEditable "foo" -->` and `<!-- #EndEditable -->`. Whenever something in the template changes, use `dwttool update project` to update the whole site. dwttool doesn't differentiate between 'raw' files (e.g. in Markdown) and builds. Basically dwttool helps to keep common parts of your pages (navigation, header, footer etc.) up to date.

**Comment by kambrium** [comment]
Just wanted to ask for an update on this pull request.

**Comment by kambrium** [comment]
Hello?

**Comment by bdougie** [comment]
Might be good to provide an example of this. Also does dwttool provide a build command? I only see the serve command.

**Comment by bdougie** [comment]
Closing for now. Please provide an example for this project to review.

**Pull request closed without merging**
