### PR TITLE
Added Pigmeat to projects list

### PR DESCRIPTION
**Pull request by limeschool**
Heyo! Just adding my static site generator, [Pigmeat](https://github.com/MadeByEmil/Pigmeat), to the project list. Check it out!

### CODE REVIEW

**Comment by zachleat** [comment]
Hey @limeschool, thanks for the PR—can you provide any context behind your project’s name and the logo?

**Comment by limeschool** [comment]
I named it after [Pigmeat Markham](https://en.wikipedia.org/wiki/Pigmeat_Markham), with the logo being a vectorized version of his depiction on the poster for [*Mr. Smith Goes Ghost*](https://www.imdb.com/title/tt0234276/), a comedy film from 1940 whose copyright expired on the promotional art (photographs of him are still copyrighted, you see, so I couldn't use those). I had just heard the song [*Here Comes The Judge*](https://www.youtube.com/watch?v=NRS62nccwmw) at the time so I just went ahead and named it after him because I often overthink what to name things, haha.

**Comment by zachleat** [comment]
Ah, I’m concerned a little bit about the history, specifically after reading this article linked up from the Wikipedia page: https://blog.wfmu.org/freeform/2010/11/the-forgotten-pigmeat-markham.html

Would there be strong resistance to a rename before we add it in here? I can help brainstorm some names if you’re open to it!

**Comment by limeschool** [comment]
Look, if you want me to rename it, maybe I will, maybe I won't, it's not like I'm invested in the name or your list.

However, the fact that you're so concerned about this puzzles me. From my point of view, you just come off as some guy with a savior complex. I'm a young, immigrant, lower-middle class gay person of color, and a social democrat too. You plug me into a calculator and it makes a goddamn happy face. I've dealt with my fair share of discrimination, and let me tell you, this is some fantastic piece of slacktivism right here that would never be of true help to anyone.

You could find racially insensitive things in the past of any historical figure, so of course Pigmeat Markham is no exception. You're not concerned about Markham as an individual, he's an excuse for you. In the very blog post you linked, he was shown as having performed as he did because it was the norm, not because he was some self-hating black man. He was an influential black American artist who made great contributions to the arts and culture of this country, and if I'd picked an influential white artist you wouldn't have batted an eye.

This performative activism on your part really does nothing but cater to imaginary strawmen you imagine would be offended over the name of a damn static site generator. I'm reminded of (this article)[https://www.thetimesnews.com/opinion/20190104/editorial-blacks-biggest-enemy-is-white-liberal] by Professor Walter E. Williams. But, eh, maybe I'll change the name to something quirky so you can boost your social credit for having taken down the big bad software project. People like you, scared that I'll ruin their Starbucks-brand of 'wokeness' with my stories of real discrimination, have always presented some sort of arbitrary challenge in the name of 'tolerance.'

I'm not doing this pissing match you're so eager for. Either add it or not, you're being ridiculous dude.

**Comment by zachleat** [comment]
Sounds like there *is* some resistance to a rename and that's fine. I think it's incredible work that you've done here and I'm personally sorry for our delay in responding here—the timing was no more than a recent sprint to close a bunch of active and old PRs in the repo. That said, I do wish you and the project all the best. If you want to discuss it further in private, feel free to email me zach@netlify.com.

**Pull request closed without merging**
