### PR TITLE
Add project Gutenberg

### PR DESCRIPTION
**Pull request by dustinmatlock**

### CODE REVIEW

**Comment by bdougie** [comment]
@dustinmatlock can you remove the startertemplaterepo fromt he frontmatter. It creates a deploy button on the page, but since Rust and Gutenberg are needed to be manually installed the deploy button does work.

Both dependencies are not available on the Netlify build images

**Comment by dustinmatlock** [comment]
It's been removed, thanks!

**Comment by dustinmatlock** [comment]
@bdougie any idea why it's saying _deploy preview failed_ since removing that portion?

**Comment by bdougie** [comment]
it's an internal build issue that I am looking into

**Comment by bdougie** [comment]
Found the issue and it was unrelated to this PR. Mainly due to the GitHub API falling over a 301 because of a username change. https://github.com/netlify/staticgen/pull/298

**Pull request merged**
