### PR TITLE
Adding igapyonv3 def

### PR DESCRIPTION
**Pull request by igapyon**
Hi Team,
I want igapyonv3 to be added to your site.
Regards,
Toshiki

### CODE REVIEW

**Comment by bdougie** [comment]
@igapyon Can you rebase the latest master branch onto your branch. That should get rid of the build failure

**Comment by igapyon** [comment]
@bdougie 
I see.
I'll try it.

**Comment by bdougie** [comment]
@igapyon sorry for the delay but I figured out the error and it is your repo needs to remvoe the github.com prefix `igapyon/igapyonv3`

**Comment by igapyon** [comment]
Thanks!
I'll check it soon.

2017-04-11 1:56 GMT+09:00 Brian Douglas <notifications@github.com>:

**Comment by bdougie** [comment]
Fixed on #257

**Pull request closed without merging**
