### PR TITLE
Add Stati

### PR DESCRIPTION
**Pull request by jfoucher**
Stati is an extensible PHP static site generator that can work with existing Jekyll sites.

### CODE REVIEW

**Comment by bdougie** [comment]
@jfoucher Do you have any examples of this working somewhere?

**Comment by jfoucher** [comment]
Hi @bdougie 
Yes, I currently generate https://jfoucher.com with it.
The build command is `stati generate` or `stati serve` to serve the generated site locally.
The docs are here : https://stati.jfoucher.com

**Comment by bdougie** [comment]
Brilliant! thanks for the quick response.

**Comment by jfoucher** [comment]
You're welcome, thanks for the merge.

**Pull request merged**
