### PR TITLE
adding ember-ghost

### PR DESCRIPTION
**Pull request by mansona**

### CODE REVIEW

**Comment by erquhart** [comment]
Cool project, thank you! Trying to determine if it qualifies as a static site generator - I don't see any way to run a build command that outputs a static site. How do you build?

**Comment by mansona** [comment]
Hey @erquhart 👋 

that's a good point 🤔 It *does* build a static site 100% (you'll see this if you use the netlify template) but I guess I need to be more explicit about what the generation command is.

Because it's built on Ember you just need to use the standard Ember build command `ember build -e production` and it will output a static site in the standard Ember output dir `dist`.

I just added this info to the main README there now to make it 100% clear 👌

**Comment by erquhart** [comment]
I guess what I'm considering is whether it's just extending something lower level - what are the chances a bunch of other essentially identical projects will pop up using the same tech underneath? This project feels more like an implementation than an engine, if that makes sense. Just trying to sort out what makes it a standalone SSG.

**Comment by mansona** [comment]
So, as I see it ember-ghost is an engine and it (currently) has 2 templates: ember-ghost-capser-template and ember-ghost-attila-template. 

The only thing that's lower down than ember-ghost in this stack is Ember itself, and I wouldn't consider that a "standalone SSG" (although almost all Ember apps can be statically rendered using [prember](https://github.com/ef4/prember) 😂)

I don't know what else you might need to get this PR merged, maybe if I started the guide that describes how to build your own ember-ghost template? I would love it if we could get it merged without me having to write that guide first because it may be a reasonable amount of effort 😖 people could get started right now by just forking [ember-ghost-casper-template](https://github.com/stonecircle/ember-ghost-casper-template) if they wanted to customise anything

**Comment by erquhart** [comment]
Alright, I'll go ahead and merge, no problem. Thanks for adding!

**Comment by mansona** [comment]
🎉 yay thanks @erquhart 

Just out of interest, how often do the github stats update? I don't see the stars and forks listed and I'm just curious if I've done something wrong 🤔

**Comment by erquhart** [comment]
They'll update within 24 hours, just waiting on the Zapier hook.

**Pull request merged**
