### PR TITLE
new generator WP Static HTML Output added

### PR DESCRIPTION
**Pull request by leonstafford**
More info of the plugin here:

 - https://github.com/leonstafford/wordpress-static-html-plugin
 - https://wordpress.org/plugins/static-html-output-plugin

FYI, an auto-deploy to Netlify option is in the works

### CODE REVIEW

**Comment by leonstafford** [comment]
@bdougie - could you please let me know what the build errors are on your end? I don't have permissions to see the build on Netlify.

Should just be another markdown file added to latest master

**Comment by bdougie** [comment]
Hey @leonstafford thanks for the PR, I am researching a fix for the failures. It has something to do with the `middleman build` script, but I have quite figured it out as of yet.

**Comment by leonstafford** [comment]
Hi @bdougie - any luck with this? I have a bit of time, if you were able to give me access to the Netlify build logs..

**Comment by bdougie** [comment]
@leonstafford can you remove the space on line 1. I did so on another branch saw it did cause a build failure

**Comment by leonstafford** [comment]
Thanks @bdougie - that seems to have cleared the error :)

**Pull request merged**
