### PR TITLE
Create hydrogen.md

### PR DESCRIPTION
**Pull request by ShailenNaidoo**
I added my static-site generator called Hydrogen to the list

### CODE REVIEW

**Comment by ShailenNaidoo** [comment]
@calavera @h3rald @zeke Hey, I would like an update about this PR please :pray:

**Comment by zeke** [comment]
Hello. Not sure why you pinged me. I'm not an owner of this repo. But hello anyway! 👋

**Comment by ShailenNaidoo** [comment]
@zeke Sorry for the ping 🙏 Not too sure who to get into contact with regarding PRs on this repo 😅

**Comment by erquhart** [comment]
Thanks, Hydrogen looks cool!

Note: [11ty](https://11ty.io) is a popular static site generator that also has a red balloon in it's branding (albeit tied to a possum). Probably not a big deal, just mentioning.

Thanks for opening!

**Comment by ShailenNaidoo** [comment]
@erquhart Thanks Shawn :pray:

**Pull request merged**
