### PR TITLE
Added Cuttlebelle

### PR DESCRIPTION
**Pull request by dominikwilkowski**

### CODE REVIEW

**Comment by erquhart** [comment]
This looks pretty cool, can't wait to try it out - thanks!

**Comment by dominikwilkowski** [comment]
Thanks for the merge, I'm going to integrate a netlify upload button as well so stay tuned :)

**Comment by erquhart** [comment]
A deploy button? But you already did 🎉 (`startertemplaterepo: cuttlebelle/website`)

screen shot 2018-01-19 at 5 39 38 pm

**Comment by dominikwilkowski** [comment]
I meant in our own readme :)

**Comment by erquhart** [comment]
Ah that makes more sense.

**Pull request merged**
